{1}{1}25
{6027}{6101}Can I have five tickets to Terrance|and Phillip's Asses of Fire, please?
{6125}{6175}No.
{6175}{6211}What do you mean, "no"?
{6211}{6263}Asses of Fire|has been rated "R"...
{6263}{6314}by the Motion Picture|Association of America.
{6314}{6361}You have to be accompanied|by a parent or guardian.
{6361}{6420}- But why?|- Because this movie|has naughty language!
{6420}{6620}- Next, please.|- [ Cash Register Rings ]