{1}{1}25
{0}{150}PIRATES OF THE CARIBBEAN|English subtitlez by tHe.b0dY
{424}{524}Drink up me 'earties yo ho!
{529}{629}We kidnap and ravage and don't give a hoot.
{644}{744}Drink up me 'earties yo ho!
{762}{862}Yo ho yo ho a pirate's life for me.
{922}{1022}We extort, we pilfer, we filch and sack.|Drink up
{1057}{1157}Quiet, missy,|cursed pirates sail these waters.
{1160}{1197}You dont want to bring them|down on us now, do ya?
{1197}{1297}Mr. Gibbs that will do!|- She was singing about pirates.
{1317}{1459}Bad luck to be singing about pirates with us|mired in this unnatural fog. Mark my words.
{1459}{1507}Consider them marked.
{1544}{1579}On your way.
{1579}{1599}Aye, Lieutenant.
{1604}{1659}Its bad luck to have a woman on board, too,
{1662}{1710}even a miniature one.
{1730}{1820}I think itd be rather exciting|to meet a pirate.
{1827}{1872}Think again, Miss Swann.
{1897}{1972}Vile and dissolute creatures,|the lot of them.
{1972}{2047}I intend to see to that any man who sails|under a pirate flag or...
{2047}{2117}...wears a pirate brand|gets what he deserves.
{2129}{2202}A short drop and a sudden stop.
{2282}{2369}Lieutenant Norrington,|I appreciate your fervor.
{2369}{2467}But Im…Im concerned about the effect|this subject will have upon my daughter.
{2467}{2522}My apologies, Governor Swann.
{2522}{2622}- Actually, I find it all fascinating.|- Yes, thats what concerns me.
{3332}{3380}Look, a boy!|Theres a boy in the water!
{3447}{3495}Man overboard!
{3602}{3627}Haul him aboard!
{3857}{3904}Hes still breathing.
{3904}{3952}Mary, Mother of God!
{4129}{4157}What happened here?
{4170}{4255}Its most likely the powder magazine.|Merchant vessels run heavily armed.
{4350}{4385}A lot of good it did them.
{4397}{4470}Everyones thinking it.|Im just saying it...
{4470}{4567}Piratas!|- Theres no proof of that.
{4567}{4602}It was probably an accident.
{4662}{4697}Rouse the Captain immediately! .|- Hay, sir.
{4709}{4759}Heave to and take in sail,|launch the boats.
{4842}{4942}Elizabeth I want you to accompany the boy.|Hell be in your charge.
{4977}{5015}Take care of him.
{5504}{5527}Its ok.
{5547}{5587}My names Elizabeth Swann.
{5612}{5672}Will Turner.
{5682}{5732}Im watching over you, Will.
{6057}{6130}- Youre a pirate!|- Has he said anything?
{6145}{6225}His name is William Turner,|thats all I found out.
{6259}{6297}Take him below.
{8062}{8112}Elizabeth!
{8137}{8174}Are you alright?
{8209}{8307}Are you decent?|- Yes, yes!
{8332}{8432}Still abed at this hour?|Its a beautiful day.
{8522}{8570}I have a gift for you.
{8667}{8715}- Oh, its beautiful!|- Isnt it?.
{8762}{8797}May I inquire as to the occasion?.
{8797}{8897}Does a father need an occasion|to dote upon his daughter?
{8929}{8952}Go on.
{9039}{9087}Actually, I, uh...
{9112}{9172}I had hoped you might wear|it for the ceremony today.
{9172}{9197}The ceremony?
{9197}{9272}Captain Norringtons|promotion ceremony.
{9280}{9317}I knew it!
{9325}{9405}Commodore Norrington|hes about to become.
{9405}{9497}Fine gentleman, dont you think.|He fancies you?
{9532}{9582}Elizabeth?|Hows it coming?
{9617}{9664}Its difficult to say.
{9664}{9732}Im told its the latest|fashion in London.
{9732}{9797}Well, women in London mustve|learned not to breathe.
{9857}{9904}My lord, you have a visitor.
{10362}{10422}Ah, Mr. Turner,|good to see you again.
{10434}{10459}Good day, sir.
{10494}{10532}I have your order.
{10697}{10797}The blade is folded steel, thats gold|filigree laid into the handle.
{10829}{10882}If I may?
{10915}{11015}Perfectly balanced. The tang is|nearly the full width of the blade.
{11095}{11145}Impressive, very impressive.
{11205}{11289}Ah, now, Commodore Norrington is|going to be very pleased with this.
{11302}{11372}Do pass my compliments|on to your Master.
{11432}{11469}I shall.
{11479}{11577}A craftsman is always pleased|to hear his work is appreciated.
{11624}{11722}- Ah, Elizabeth, you look absolutely stunning.|- Will.
{11747}{11795}So good to see you!
{11805}{11902}- I had a dream about you last night.|- About me?
{11902}{11962}Elizabeth, is that entirely|proper for you to...?
{11962}{12005}About the day we met,|do you remember?
{12005}{12055}How could I forget, Miss Swann?
{12055}{12129}Will, how many times must|I ask you to call me Elizabeth?
{12129}{12214}At least once more,|Miss Swann, as always.
{12214}{12297}There, see.
{12297}{12312}At least the boy has|a sense of propriety.
{12312}{12372}Now, we really must be going.|Farewell.
{12404}{12467}Good day, Mr. Turner.
{12477}{12515}Come along.
{12587}{12622}Good day...
{12682}{12707}...Elizabeth.
{14967}{14989}What?
{14992}{15055}Hold up there, you.
{15075}{15162}Its a shilling to tie up your|boat at the dock.
{15220}{15270}And I shall need to|know your name.
{15317}{15415}What dye say to three shillings|and we forget the name?
{15509}{15557}Welcome to Port Royal, Mr. Smith.
{16474}{16527}Two paces front!
{16579}{16642}Right about turn!
{16700}{16740}Present...
{16740}{16775}...arms!
{17362}{17432}This dock is off limits to civilians.
{17432}{17505}Im terribly sorry, I didnt know.|If I see one...
{17505}{17555}...I shall inform you immediately.
{17625}{17722}Apparently theres some sort of a high toned|and fancy to do up at the fort, eh?
{17722}{17867}How could it be that two upstanding gentlemen|such as yourselves did not merit an invitation?
{17867}{17952}Someone has to make sure this|dock stays off limits to civilians.
{17952}{18052}Its a fine goal to be sure but|it seems to me that a...
{18059}{18159}a ship like that makes this one|here a bit superfluous, really.
{18179}{18274}Ah, the Dauntless is the power in these waters,|true enough, but theres no ship...
{18274}{18347}...that can match the|Interceptor for speed.
{18347}{18447}Ive heard of one, supposed to be|very fast, nigh un-catchable...
{18470}{18517}"The Black Pearl"
{18565}{18650}Well…theres no real ship that|can match the Interceptor.
{18687}{18782}- The Black Pearl is a real ship.|- No, no its not.
{18782}{18849}- Yes, it is, Ive seen it.|- Youve seen it?
{18849}{18929}- Yes.|- You havent seen it.
{18929}{18954}Yes, I have.
{18954}{19054}Youve seen a ship with black sails...
{19054}{19147}...thats crewed by the damned and|captained by a man so evil...
{19147}{19247}...that Hell itself spat him back?|- Ne.
{19272}{19307}Ne.
{19307}{19392}But I have seen a ship|with black sails.
{19392}{19492}Oh, and no ship thats not crewed by|the damned and captained by a man so evil...
{19500}{19550}...that Hell itself spat him|back out could possibly...
{19550}{19597}...have black sails therefore couldnt|possibly be any other ...
{19597}{19679}...ship than the Black Pearl.|Is that what you're saying?
{19704}{19747}Ne.
{19747}{19847}Like I said… theres no real ship|that can match the Interceptor
{19917}{19954}Hey!
{19972}{20030}You!
{20030}{20122}Get away from there!|You dont have permission to be aboard there, mate.
{20122}{20197}Im sorry, its just its such|a pretty boat  ship!
{20197}{20290}- Whats your name?|- Smith or...Smithy, if you like.
{20290}{20380}Whats your purpose in|Port Royal, Mr. Smith?
{20380}{20422}Yeah, and no lies!
{20422}{20562}Well, then, I confess, it is my intention|to commandeer one of these ships.
{20562}{20662}Pick up a crew in Tortuga,  raid, pillage, plunder|and otherwise pilfer my weasely black guts out.
{20679}{20727}I said no lies.
{20727}{20757}I think hes telling the truth.
{20757}{20847}If he were telling the truth,|he wouldnt have told us.
{20847}{20947}Unless, of course, he knew you wouldnt|believe the truth even if he told it to you.
{21205}{21230}May I have a moment?
{21469}{21569}You look lovely, Elizabeth.|- Yes?
{21572}{21780}I apologize if I seem forward but I...|must speak my mind
{21782}{21882}This promotion throws into sharp|relief that which I have...
{21912}{22037}...not yet achieved.|A marriage to a fine woman.
{22072}{22154}You have become a fine|woman, Elizabeth.
{22154}{22197}I cant breathe.
{22197}{22277}Yes, Im a bit nervous myself.
{22347}{22412}...and then they made me their chief.
{22454}{22497}Elizabeth?
{22555}{22597}Elizabeth!
{22647}{22697}The rocks!|Sir, its a miracle she missed them!
{22772}{22832}- Will you be saving her then?|- I cant swim.
{22882}{22944}Pearl of the Kings Navy you are.
{22944}{22982}Do not lose these.
{23347}{23395}What was that?
{24447}{24472}I got her.
{24482}{24557}- Not breathing.|- Move!
{24719}{24757}Never would have thought of that.
{24757}{24844}Clearly youve never been to Singapore.
{24969}{25020}Where did you get that?
{25057}{25082}On your feet.
{25157}{25195}Elizabeth.
{25207}{25295}- Are you alright?|- Yes, Im fine.
{25395}{25432}- Shoot him!|- Father!
{25447}{25544}Commodore, do you really|intend to kill my rescuer?
{25697}{25769}I believe thanks are in order.
{25857}{25920}Had a brush with the East India|Trading company, did we?
{25920}{25970}Pirate?
{25987}{26020}- Hang him.
{26020}{26120}Keep your guns on him, men.|Gillette, fetch some irons.
{26145}{26245}- Well, well... Jack Sparrow, isnt it?|- Captain Jack Sparrow, if you please, sir.
{26294}{26394}- Well, I dont see your ship...Captain.|- Im in the market as it were.
{26444}{26532}- He said hed come to commandeer one.|- Told ya he was telling the truth.
{26532}{26594}These are his, sir.
{26644}{26732}No additional shots nor powder...
{26757}{26832}A compass that doesnt point north...
{26932}{27007}And I half expected it|to be made of wood.
{27057}{27144}You are, without doubt, the worst|pirate Ive ever heard of.
{27154}{27219}But you have heard of me.
{27269}{27319}Commodore, I really must protest.
{27349}{27374}Carefully Lieutenant.
{27374}{27432}Pirate or not this man saved my life.
{27432}{27527}One good deed is not enough to redeem|a man of a lifetime of wickedness.
{27527}{27590}Though it seems enough|to condemn him.
{27590}{27632}Indeed.
{27645}{27682}Finally.
{27720}{27745}No, dont shoot!
{27745}{27845}I knew youd warm up to me.|Commodore Norrington, my effects, please...
{27845}{27890}...and my hat.
{27919}{27939}Commodore!
{28007}{28107}- Elizabeth, it is Elizabeth isnt it?|- Its Miss Swann.
{28107}{28207}Miss Swann, if youd be so kind.|Come, come, dear, we dont have all day.
{28269}{28319}Now if youd be very kind..
{28707}{28782}Easy on the goods, darling.
{28782}{28844}Youre despicable.
{28844}{28944}Sticks and stones, love. I saved your|life, you saved mine, were square.
{28979}{29044}Gentlemen, mlady.
{29044}{29124}you will always remember this as|the day that you almost caught...
{29124}{29182}...Capitan Jack Sparrow.
{29657}{29739}- Now, will you shoot him?|- Open fire!
{29914}{29949}On his heels!
{30419}{30519}Gillette, Mr. Sparrow has a dawn|appointment with the gallows...
{30519}{30574}...I would hate for him to miss it.
{33107}{33207}Right where I left you.
{33332}{33357}Not where I left you.
{33620}{33670}You're the one they're hunting.
{33695}{33732}The pirate.
{33932}{33994}Ah. Well, then it would be a shame to|put a black mark on your record.
{33994}{34032}So, if you'll excuse me...
{34129}{34187}Do you think this wise, boy...
{34187}{34245}...crossing blades with a pirate?
{34280}{34320}You threatened Miss Swann.
{34400}{34457}Only a little.
{34757}{34844}You know what youre doing,|Ill give you that. Excellent form...
{34857}{34919}...but hows your footwork?
{34919}{35020}If I step here...|Very good.
{35037}{35080}Now I step again.
{35207}{35240}Ta.
{35732}{35784}That is a wonderful trick.
{35794}{35895}Except once again you are|between me and my way out.
{35897}{35980}And now you have no weapon.
{36532}{36569}Who makes all these?
{36614}{36695}I do!|And I practice with them...
{36707}{36745}...three hours a day!
{36777}{36837}You need to find yourself a girl, mate.
{37027}{37122}Or, perhaps the reason you practice three|hours a day is that you already found one ...
{37122}{37222}...and are otherwise incapable|of wooing said strumpet.
{37234}{37279}You're not a eunuch, are you?
{37294}{37369}I practice three hours a day,|so that when I meet a pirate...
{37369}{37407}...I can kill it.
{39327}{39355}You cheated.
{39372}{39392}Pirate.
{39470}{39520}- Move away.|- No.
{39532}{39594}- Please, move.|- No!
{39594}{39644}I cannot just step aside|and let you escape.
{39719}{39779}This shot is not meant for you.
{40032}{40070}Move in!
{40145}{40282}Excellent work, Mr. Brown . Youve assisted|in the capture of a dangerous fugitive.
{40282}{40347}Just doing my civic duty, sir.
{40357}{40437}Well, I trust youll always remember|this as the day that Captain...
{40439}{40519}...Jack Sparrow almost escaped.
{40519}{40569}Take him away!
{40744}{40787}- Can you smell it.
{40789}{40890}- Nice juicy bone.|- Come here, boy.
{40900}{41000}You can keep doing that forever,|the dog is never going to move.
{41007}{41107}Oh, excuse us if we haven't resigned|ourselves to the gallows just yet.
{42094}{42194}- Has my daughter given you an answer yet?|- No, she hasnt.
{42237}{42289}Well, she has had a very trying day.
{42332}{42372}Ghastly weather, dont you think?
{42392}{42427}Bleak, very bleak.
{42474}{42494}Whats that?
{42532}{42552}Cannon fire!
{42612}{42652}Return fire!
{42657}{42757}I know those guns.
{42867}{42942}- Its the Pearl.|- Black Pearl?
{43014}{43114}Ive heard stories. Shes been preying on|ships and settlements for near ten years.
{43127}{43227}- Never leaves any survivors.|- No survivors?
{43249}{43314}Then where do the stories|come from, I wonder?
{45792}{45824}Goveror.
{45824}{45892}Barricade yourself in my office.
{45940}{45975}Thats an order!
{46442}{46462}Don`t...
{46472}{46507}Hello, chump.
{46619}{46639}Girl.
{46897}{46947}SMiss Swann, theyve come to kidnap you.
{46965}{47015}- What?|- Youre the Governors daughter.
{47109}{47184}They havent seen you. Hide and the|first chance you get, run to the fort.
{47444}{47469}Gotcha!
{47657}{47720}- Its hot! Its on me!|-Come on.
{48809}{48877}We know youre here, Poppet.
{48892}{48934}Poppet.
{48934}{48954}Come out.
{48987}{49037}We promise we wont hurt you.
{49119}{49157}We will find you, Poppet.
{49197}{49285}Youve got something of|ours and it calls to us.
{49447}{49497}The Gold calls to us...
{49540}{49589}Gold, gold.
{49722}{49742}Hello, Poppet.
{49789}{49837}- Parley|- What?
{49854}{49924}Parley. I invoke the right of parley.
{49944}{50022}According to the code of the brethren, set down|by the pirates Morgan and Bartholomew...
{50025}{50050}...you have to take me to your Captain.
{50060}{50110}I know the code.
{50115}{50170}If an adversary demands parley you|can do them no harm until ...
{50177}{50200}...the parley is complete.
{50207}{50237}To blazes with the code.
{50237}{50290}She wants to be taken to the Captain.
{50332}{50482}And shell go without a fuss.|We must honor the code.
{50754}{50794}Say goodbye!
{50905}{50925}Goodbye.
{51052}{51085}- Come on!|- Elizabeth.
{51322}{51359}Outta my way, scum!
{51679}{51762}My sympathies friend, youve|no manner of luck at all.
{52314}{52352}Come on, doggy.
{52357}{52432}Its just you and me now.|Its you and ol Jack.
{52437}{52494}Come on. Come on.
{52507}{52592}Good boy. Thats it.|Good boy, come on.
{52592}{52647}Bit closer, bit closer.
{52650}{52725}Thats it, thats it, doggy.
{52727}{52790}Come on you filthy, slimy, mangy cad.
{52845}{52902}No, no, no, no, no,|I didnt mean it. I didnt.
{53092}{53129}This aint the armory.
{53144}{53244}Well, well, well,|look what we have here Twigg?
{53267}{53322}Capitain Jack Sparrow.
{53354}{53517}Last time I saw you, you were all|alone on a godforsaken island.
{53517}{53617}Shrinking into the distance.|His fortunes arent improved much.
{53647}{53725}Worry about your own|fortunes, gentlemen.
{53730}{53829}The deepest circle of Hell is reserved|for betrayers and mutineers.
{53949}{53987}So there is a curse.
{54044}{54069}That's interestin.
{54077}{54124}You know nothing of Hell.
{54342}{54390}Thats very interesting.
{55287}{55322}I didnt know we were|takin on captives.
{55347}{55422}Shes invoked the right of parley|with Captain Barbossa.
{55429}{55514}- I am here to negotiate...|- You will speak when spoken to.
{55547}{55647}And yell not lay a hand on those|under the protection of parley.
{55667}{55709}Aye, sir.
{55774}{55799}My apologies, Miss.
{55850}{55950}Captain Barbossa, I am here to negotiate|the cessation of hostilities l ...
{55962}{55997}...against Port Royal.
{56010}{56110}There are a lot of long words in there, Miss,|were naught but humble pirates.
{56145}{56242}- What is it that you want?|- I want you to leave and never come back.
{56302}{56352}Im disinclined to acquiesce to your request...
{56419}{56457}...means no.
{56504}{56554}Very well.
{56592}{56612}I'll drop it.
{56745}{56837}Me holds are burstin' with swag and|that bit of shine matters to us?
{56870}{56957}- Why?|- Its what youve been searching for.
{56992}{57077}I recognized the ship. I saw it eight years|ago on the crossing from England.
{57087}{57119}Did ya now?
{57189}{57237}Fine.
{57239}{57339}Well, I suppose if it is worthless then|theres no point in me keeping it.
{57637}{57692}You have a name, Missy?
{57715}{57780}Elizabeth... Turner
{57815}{57865}Im a maid in the|Governors household.
{57944}{57969}Miss Turner.
{58042}{58062}Bootstrap.
{58174}{58237}And how does a maid come to|own a trinket such as that?
{58239}{58297}Family heirloom, perhaps?
{58329}{58405}I didnt steal it if thats what you mean.
{58405}{58505}Very well, you hand it over and well put your|town to our rudder and never return.
{58864}{58897}Our bargain?
{58969}{59032}Still the guns and stowem, ...The men.
{59052}{59152}Wait! You have to take me to shore.|According to the code of the order of the brethren...
{59152}{59250}First, your return to shore was|not part of our negotiations...
{59250}{59307}...nor our agreement so|I must do nothing.
{59307}{59407}And secondly, you must be a pirate for|the pirates code to apply and youre not
{59407}{59542}And thirdly, the code is more what you'd|call "guidelines" than actual rules.
{59542}{59634}Welcome aboard the Black Pearl,|Miss Turner.
{60165}{60212}Theyve taken her.|Theyve taken Elizabeth.
{60227}{60285}Mr. Murtogg, remove this man.
{60285}{60362}We have to hunt them down,|we must save her.
{60362}{60410}And where do you propose we start?
{60429}{60524}If you have any information concerning|my daughter, please, share it.
{60589}{60689}That Jack Sparrow.|He talked about the Black Pearl.
{60692}{60749}Mentioned it, is more what he did.
{60784}{60807}Ask him where it is.
{60812}{60865}Make a deal with him|he could lead us to it.
{60865}{60910}No...
{60910}{60987}the pirates who invaded this Fort left|Sparrow locked in his cell ergo....
{60987}{61042}...they are not his allies.
{61042}{61112}Governor, we will establish|their most likely course...
{61122}{61165}Thats not good enough!
{61190}{61289}Mr. Turner, you are not a military|man, you are not a sailor.
{61347}{61447}You are a blacksmith and this is|not the moment for rash actions.
{61519}{61582}Do not make the mistake of thinking|you are the only man here...
{61584}{61619}...who cares for Elizabeth.
{61920}{61937}You!
{61937}{61980}- Sparrow.|- Aye.
{61980}{62035}You are familiar with that ship,|the Black Pearl?
{62072}{62119}- Ive heard of it.|- Where does it make berth?
{62127}{62209}Where does it make berth?|Have you not heard the stories?
{62279}{62452}Captain Barbossa and his crew of miscreants|sailed from the dreaded Isla de Muerta.
{62452}{62552}Its an island that cannot be found except|by those who already know where it is.
{62590}{62622}The ships real enough.
{62647}{62717}Therefore its anchorage must be|a real place. Where is it?
{62740}{62822}- Why ask me?|- Because youre a pirate.
{62827}{62887}And you want to turn pirate|yourself, is that it?
{62927}{62949}Never.
{63044}{63127}- They took Miss Swann .|- Oh, so it is that youve found a girl.
{63127}{63182}I see.
{63182}{63324}Well, if youre intending to brave all, hasten|to her rescue and so win fair ladys heart...
{63324}{63425}...youll have to do it alone, mate.|I see no profit in it for me.
{63452}{63532}- I can get you out of here.|- Hows that? The keys run off.
{63537}{63625}I helped build these cells.|These are half pin-barrel hinges.
{63672}{63740}With the right leverage and|a proper application of strength...
{63784}{63812}...the door will lift free.
{63877}{63957}- Whats your name?|- Will Turner.
{63992}{64042}That will be short for William,|I imagine.
{64042}{64142}Good, strong name. No doubt,|named for your father, aye.
{64192}{64222}Yes.
{64290}{64355}Aha. Well, Mr. Turner,|Ive changed me mind.
{64375}{64445}If you spring me from this cell,|I swear on pain of death...
{64445}{64545}...I shall take you to the Black|Pearl and your bonny lass?
{64545}{64644}- Do we have an accord?
{64694}{64754}- Agreed.|- Agreed, get me out.
{64857}{64887}Hurry, someone will|have heard that.
{64892}{64932}Not without my effects.
{65105}{65135}Were going to steal a ship?
{65200}{65215}That ship?
{65215}{65315}Commandeer.|Were going to commandeer that ship.
{65317}{65347}Nautical term.
{65377}{65417}One question about your business boy,|or theres no use going.
{65459}{65559}This girl, how far are you|willing to go to save her?
{65572}{65624}- Id die for her.|- Oh, good.
{65632}{65667}No worries, then.
{66167}{66225}This is either madness or brilliance.
{66245}{66327}Its remarkable how often|those two traits coincide.
{67077}{67162}Everyone stay calm,|we are taking over the ship.
{67162}{67217}Aye, avast!
{67299}{67347}This ship cannot be crewed by two men.
{67377}{67412}You'll never make it out of the bay.
{67442}{67469}Son.
{67489}{67590}Im Captain Jack Sparrow, savvy?