{1}{1}25
{80}{136}Forever.
{120}{250}To the Butcher!
{409}{466}Why don't you get out of here, Johnny?
{532}{568}Go on. Go!
{980}{1070}Is there anyone in the Five Points|you haven't fucked?
{1034}{1052}Yes!
{1062}{1072}You!
{1346}{1392}Belt down!
{1666}{1720}Try it and I'll bite ya.
{1723}{1778}You were gonna bite me.
{1776}{1830}I dont think you want me.
{1802}{1854}Find out.
{2628}{2662}Oh, Jenny!
{3722}{3772}I can't sleep.
{3911}{4098}I hope you don't mind us|laying here, sir?
{4029}{4138}Whatever takes your fancy,|young friend.
{4356}{4432}Is your shoulder keeping you up?
{4414}{4504}I don't sleep too much.
{4494}{4618}I sleep with one eye open. I only|got one eye.
{4706}{4784}How old are you Amsterdam?
{4888}{5072}Not too sure. Never did|figure it.
{5024}{5114}I'm 47.
{5122}{5186}47 years old.
{5268}{5436}You know how I stayed alive|this long? All these years.
{5418}{5458}Fear!
{5504}{5610}The spectacle of fearsome acts.
{5606}{5746}Somebody steals from me, I cut|off his hands.
{5676}{5816}He offends me, I cut out his tongue.
{5760}{5970}He rises against me, I cut off his|head, stick it on a pike!
{5896}{6044}Raise it high up, so all in the|streets can see.
{6022}{6122}That's what preserves the order|of things.
{6186}{6220}Fear.
{6292}{6436}That one tonight. Who was he?
{6426}{6608}A nobody. A coward.
{6588}{6734}What an end that|would have been.
{6706}{6873}I killed the last honourable man|15 years ago.
{6831}{6880}Since then....
{6936}{7008}You've seen his portrait downstairs?
{7092}{7172}Has your mouth been glued up with juice?
{7131}{7198}I asked you a question!
{7164}{7236}I said I've seen it, sir.
{7350}{7486}You got a murderous rage in you.|I like it.
{7431}{7581}So much life boiling up in you.|That's good!
{7614}{7773}The priest and me lived by the|same principles.
{7773}{7876}Only faith divided us.
{7909}{7981}He gave me this you know?
{8090}{8200}That was the finest beating I|ever took.
{8184}{8408}My face was pulp. My guts pierced.|My ribs all messed up.
{8424}{8504}When he came to finish me...
{8590}{8668}...I couldn't look him in the eye.
{8798}{8874}He spared me because...
{8874}{8964}....he wanted me to live in shame.
{8920}{8988}This was a great man.
{9040}{9092}A great man.
{9162}{9264}So I cut out the eye that|looked away.
{9306}{9404}Sent it to him wrapped in|blue paper.
{9392}{9514}I would've cut them both out if I|could afford being blind.
{9522}{9622}I rose up again with a full heart...
{9600}{9694}...and buried him in his own blood.
{9888}{9920}Well done!
{10004}{10126}He was the only man I killed|worth remembering.
{10370}{10442}I never had a son.
{10628}{10722}Civilisation is crumbling.
{11136}{11188}God bless you!
{11928}{12000}If you've got anything to say...
{12010}{12082}...now is the time to say it.
{12084}{12140}Who is he to you, Jenny?
{12282}{12352}I was 12 years old.
{12350}{12474}My mother was dead. I was living|in a doorway.
{12494}{12802}He took me in. Took care of me in|his own way.
{12792}{12872}After they cut out the baby...
{12922}{13041}He doesn't fancy girls that|scarred up.
{13168}{13330}You should know, in your own mind...
{13306}{13450}...that he never laid a hand on me|till I asked him too.
{13941}{14002}Who are you?
{14018}{14086}Who are you?
{15916}{16262}Gentlemen, you are most welcome to|this palace of enchantment...
{16102}{16498}...with visions to rival the tales of|Sheherazade and the Arabian Nights!
{16880}{16978}Flex your head to the teutonic beauty!
{16944}{17068}Feast you eyes on the magnificent blue...
{17034}{17098}...of these creatures.
{17082}{17236}Gentlemen, you see our caged birds well!
{17176}{17302}How would you like to make them sing?
{17252}{17496}They could be singing for you.
{17546}{17720}May God put the spirit of the|holy steel in my spine...
{17666}{17804}...and the love of the blessed|Virgin in my heart.
{17818}{17860}Amen.
{17954}{18104}Easy now. What did you say?
{18050}{18134}He's not who he says he is.
{18138}{18212}He's not who he says he is?
{18292}{18398}Count you blessings he considers|you a friend!
{18398}{18598}The only thing he considers every day|and night is how to kill you!
{18566}{18690}Those eyes want me to take|them out for you!
{18668}{18776}I'll bury it up you fundunem where|it belongs!
{18740}{18852}I can read right through them!|They're empty...
{18796}{18846}His name is Vallon.
{18888}{18940}Don't do it Bill!
{18928}{18978}His name is Vallon!
{19742}{19838}Curious people these celestials.
{19842}{19918}You know why they use short|sleeves?
{19894}{19992}So everyone can see he's got|nothing stashed.
{19958}{20052}I hope it doesn't become a fashion.
{20184}{20208}Johnny?
{21122}{21154}Get up!
{21524}{21766}Ladies and gentlemen, if I may have|your kind attention.
{21644}{21760}As some of you have surely|noticed...
{21714}{21890}...our friend and benifactor, Mr Cutting...
{21812}{22094}..is tonight wearing a waistcoat|of certain distinction!
{22068}{22238}May we appeal to him, to favour us...
{22154}{22270}...with another exciting exhibition.
{22224}{22520}Of skill. Courage. Daring and drama!
{22854}{22896}What's gonna happen?
{23566}{23620}The spider's kiss!
{23680}{23726}The wheel of death!
{23718}{23768}William Tell!
{23756}{23782}The butterfly!
{23804}{23848}The spider's kiss!
{23840}{23914}The Butcher's apprentice!
{23896}{23948}The Butcher's apprentice!
{23928}{24036}A command performance!
{24036}{24080}Where have you been?
{24066}{24174}A command performance indeed.
{24132}{24178}I want you to get out of here!
{24170}{24320}And for this, I must beg the|indulgence...
{24244}{24288}...of my former...
{24266}{24376}... assistent in matters of impailment...
{24352}{24462}...the Butcher's original apprentice.
{24454}{24512}What do you say, Jen?
{24492}{24600}One more time for the|sweet souvenir.
{24580}{24602}Come on!
{24846}{24914}Don't do it!
{25180}{25232}She'll be alright.
{25296}{25338}Remember this?
{25322}{25344}Of course!
{25580}{25768}You may feel more comfortable without|that garment, Miss Everdeane!
{25727}{25824}You'll have to filch me a|new one, Bill!
{26124}{26218}Anything in your pockets tonight?
{26188}{26277}I ain't started working yet.
{26320}{26424}What about that locket I| gave you?
{26756}{26868}Apologies my dear. Pick it up.
{26950}{27020}Whoopsie daisy!
{27048}{27122}Now its good and broke!
{27124}{27224}I can't seem to get anything|right tonight.
{27372}{27510}You got the sand to give 'm a|grand finale?
{27664}{27768}Maybe when you're aiming a|little straighter.
{27976}{28052}Enough of this heathen music.
{28038}{28132}Get rid of these goddamn monkeys.
{28089}{28133}Strike up boys!
{28152}{28280}This is a night for Americans!
{28420}{28444}Jenny!
{29798}{29844}Hats off!
{30000}{30188}We hold in our hearts the memory|of our fallen brothers...
{30122}{30236}...whose blood stains the very streets...
{30180}{30242}...we walk today.
{30250}{30500}Also on this night, we pay tribute|to the leader of our enemies.
{30426}{30508}An honourable man...
{30492}{30682}...who crossed over bravely.|Fighting for what he believed in.
{30764}{30944}To defeat my enemy, I extinguish|his life...
{30876}{31004}... and consume him as I consume|these flames.
{31004}{31094}In honour of Priest Vallon.
{31108}{31154}In honour of Priest Vallon!
{31262}{31333}That's a wound !
{31532}{31706}I want you all to meet the son of|Priest Vallon.
{31648}{31730}I took him under my wing...
{31716}{31792}...and see how I'm repaid.
{31772}{31910}He saved my life one day so he|could kill me the next...
{31839}{31910}...like a sneak thief.
{31886}{31960}Instead of fighting like a man.
{31968}{32156}A base defiler. Unworthy of|a noble name.
{32386}{32477}That'll do Mcgloin.|Spread him out.
{32489}{32652}I hate blackies. You..you get to watch.
{32732}{32806}This is fresh meat!
{32830}{32928}We need to tenderise this meat|a bit.
{32914}{33066}Alright, lets kiss goodnight to|that pretty face of yours!
{33252}{33300}No.......!
{33332}{33532}What'll it be then. Rib or chop.|Loin or shank.
{33432}{33454}The liver!
{33442}{33466}The spleen!
{33486}{33512}The kidney!
{33670}{33694}The lung!
{33690}{33716}The liver!
{33726}{33748}The tongue!
{33796}{33862}The heart! The heart!
{33830}{33886}The heart?
{33866}{33942}This boy has no heart.
{33904}{34022}Then kill him!
{34094}{34174}He ain't earned the death!
{34144}{34256}He ain't earned the death of|my hands!
{34248}{34390}He'll walk amongst you marked|with shame.
{34318}{34544}A freak. Worthy of Barnum's|museum of wonders.
{34456}{34632}God's only man, speared by|the Butcher.
{35488}{35632}Here. Here. This way.
{35560}{35600}Come on.
{36704}{36780}I want to show you something.
{36884}{36970}My mother's bones share this|grave.
{37000}{37144}I've saved 20 cents out of every|dollar I've ever earned since ....
{37072}{37122}...I was thirteen.
{37166}{37248}That's 215 dollars.
{37236}{37316}For bludgeoning and the rest.
{37394}{37508}This is what I wanted to show you.
{37498}{37626}This is where we're going to go,|as soon as you get better....
{37574}{37744}...San Fransisco, California.
{37724}{37816}You can have anything you want|out there.
{37812}{37964}These men are pulling gold right|out of the river.
{37900}{37956}With their own hands.
{37984}{38156}We're here and need to get there.
{38118}{38170}Start here.
{38170}{38296}Go down 'round here.
{38302}{38364}Up to San Francisco.
{38400}{38460}The shortest way to go.
{38474}{38530}Will you go with me?
{39118}{39246}No need to fire that, miss.|Or even aim it.
{39222}{39332}An audience with yor mangled|friend is all I want.
{39684}{39762}I've 44 notches on my club.
{39776}{39836}Do you know what they are for?
{39876}{39962}To remind me of what I owe God|when I die.
{40114}{40200}My father was killed in battle too.
{40198}{40282}In Ireland, in the streets.
{40312}{40404}Fighting those who were taking|their privilege.
{40378}{40452}What only could be got and held...
{40416}{40502}...by the decimation of a race.
{40500}{40606}That war is a thousand years old|and more.
{40600}{40684}We never expected it to follow|us here.
{40712}{40742}It didn't.
{40764}{40836}It was waiting for us when|we landed.
{40916}{41072}Your father tried to carve out a|corner in this country for his tribe.
{41066}{41142}That was him. That was his Dead Rabbits.
{41204}{41312}I often wondered, if he'd lived a|bit longer...
{41310}{41392}...would he have wanted it to|be more.
{41644}{41748}Why did you rifle through his|pockets then?
{42134}{42194}For safekeeping.
{42264}{42326}I thought maybe you could do|with it.
{42848}{42928}Blood stays on the blade.
{44748}{44836}That's a sorry looking pelt.
{44912}{45066}And it's been so nice and quiet|for the last three months.
{45060}{45204}Tell me, this charge. Does it sit|on easy with you?
{45176}{45392}No. Not uneasy , Bill.
{45324}{45402}I wouldn't say that.
{45432}{45640}But.....my allegiance is|to the law.
{45584}{45680}I'm paid to uphold the law.
{46026}{46140}What in heaven's name are you|talking about?
{46210}{46422}You may have misgivings, but don't go believing|that, Jack. That way lies damnation.
{46420}{46508}I'm in no danger of|damnation, Bill.
{46762}{46818}Here's the thing.
{46844}{46998}I don't give a fuck about your moral conflicts...
{46922}{46992}..you meatheaded shit sack.
{47020}{47094}That's more or less the thing.
{47118}{47248}I want you to go out there. You|and nobody else.
{47200}{47254}None of your little minions.
{47226}{47304}I want you to go out there...
{47308}{47366}...and I want you...
{47380}{47542}...to punish, the person...
{47478}{47564}...who's responsible...
{47592}{47766}...for murdering this poor|little rabbit.
{47846}{47906}Is that understood?
{47990}{48026}Right!
{48062}{48192}Help yourself to some decent meat|on the way out.
{49040}{49064}Damn it!
{49120}{49174}Is that you, boy?
{49202}{49308}I didn't mean nothing by that shot|you know?
{49294}{49360}You scared me is all.
{49412}{49516}You know I'd never do you harm.
{49502}{49568}Come out now, lad.
{49612}{49694}Remember your father and me?
{49752}{49884}Are you to young to remember your Uncle Jack?
{49882}{49968}The times we had.
{50086}{50152}You know I won't hurt you.
{50914}{50974}This is bad for everybody.
{50944}{51028}What's next, dead politicians?
{51042}{51146}I could spare half a dozen|of you...
{51110}{51178}...easier than I can spare him.
{51184}{51328}Still, I think it shows dash.
{51279}{51417}Give the boy some time, we'll|settle with a good dust up.
{52129}{52176}The lads!
{52415}{52550}There are more of us coming off|the ships each day.
{52512}{52614}I heard 15,000 Irish a week.
{52626}{52702}And we're afraid of the Natives!
{52734}{52790}Get all of us together...
{52762}{52826}....we ain't got a gang..
{52804}{52852}...we got an army.
{52841}{53050}And all we need is a spark. One|spark, to wake us all up.
{53379}{53444}It was me who played you false.
{53478}{53544}I'd take it back if I could.
{53510}{53567}Take it back?
{53650}{53722}Johnny, I ought to kill you!
{54041}{54144}Get out of the Points and|don't come back.
{54304}{54354}Where are you going, boil?
{54382}{54414}Come along.
{54426}{54454}Come on.
{54524}{54610}Tell us John, what's the trouble?
{54616}{54672}No trouble, Bill.
{54729}{54810}Still hiding out with| your friends?
{54866}{55041}No, I'm not with them, Bill.
{54984}{55096}I'm with you, with the Natives.
{55167}{55324}You always were a Native, as far|as I'm interested, John.
{55322}{55414}Till you became a stag.
{55479}{55562}You tell me you're a Native?
{55520}{55582}Do you want to know what|a Native is?
{55614}{55876}A Native is a man, who's|willing to give his life...
{55772}{55838}...for his country.
{55855}{55940}Like my father done.
{55990}{56116}Are you willing to do that,| my young friend?
{56294}{56374}John? Johnny?
{56555}{56588}Johnny?
{56822}{56855}I'll get you off.
{57174}{57246}It hurts too much.
{57384}{57434}Just kill me.
{57546}{57608}Just kill me.
{57641}{57738}Please. Please.
{57854}{57966}Please. Please.
{58008}{58038}Please.
{58154}{58210}I'm sorry, Johnny.
{58594}{58696}Oh, Mary mother of God, pray|for us sinners...
{58646}{58740}...on the day of our death...amen.
{58744}{58808}Rest in peace, Ma.
{58864}{58920}What are you doing here, boil?
{59076}{59179}What's that nigger doing in| this church?
{59255}{59358}What's a Dead Rabbit doing with|the Natives,huh?
{59308}{59388}No niggers among the Natives.
{59348}{59420}Niggers as robbers is|one thing...
{59384}{59502}...but niggers in a church,|that's something else!
{59460}{59526}You run with the Natives, you go|pray with the Natives!
{59494}{59616}You're going to wind up on a stake|like your man did!
{59574}{59602}McGloin?
{59620}{59782}Father! Jezus, do you know there's|a nigger in your church?
{60160}{60217}Jezus!
{60760}{60816}The earth turns...
{60836}{60920}...but we don't feel it move.
{60964}{61044}And one night you look up...
{61055}{61272}...one spark and the skie's on fire.
{61454}{61534}It's a touching spectacle.
{61558}{61666}We'll come back when you're|ready for us.
{61790}{61905}The past is the torch that|lights our way.
{61886}{61978}Where our fathers have shown|us the path.
{61960}{62020}We shall follow.
{62058}{62210}Our faith is the weapon most|feared by our enemies...
{62164}{62266}...for thereby shall we lift our|people up...
{62214}{62314}...against those who will|destroy us.
{62290}{62500}Our name is called the Dead Rabbits,|to remind all of our suffering...
{62410}{62522}...and as a call to those who|suffer still...
{62466}{62534}...to join our ranks.
{62512}{62740}However so far they may have strayed|from our common home across the sea.
{62626}{62817}For with great numbers, must come|great strength.
{62741}{62828}For the salvation of our people.
{62828}{62872}We don't want your business.
{62850}{62890}How many other men live here?
{62882}{62924}You all have to register.
{62902}{62988}You can't force me to join|no army.
{62954}{62996}Have you got 300 dollars?
{62976}{63002}Of course not!
{62988}{63055}Who the hell's got 300 dollars?
{63022}{63166}If you are drafted, release from militairy| service can only be secured...
{63104}{63224}...for 300 dollars, according to|the conscription act.
{63164}{63191}300 Dollars?
{63178}{63238}Otherwise you have to serve!
{63208}{63278}Who the hell's got 300 dollars?
{63241}{63278}You have to serve, sir!
{63260}{63290}You tell me!
{63322}{63350}Boys!
{63386}{63494}I was born here, sir. You|immigrated here!
{63484}{63605}Sweet jezus. War does terrible|things to men.
{63562}{63638}Get back up town, where you|belong!
{63600}{63734}300 dollars. It's another rich|man's war!
{63710}{63808}Sir, I request an audience|with this man.
{63824}{63910}Don't they speak English in|New York anymore!
{63879}{63938}Don't understand.
{63908}{63958}You do speak English!
{63976}{64191}I wonder if miss Everdeane can angle| her rifle in another direction?
{64210}{64391}I wonder Mr. Vallon, if you understand|the value of this sort of publicity?
{64376}{64578}The Archbishop himself, shoulder to shoulder|with half the Irish in the Five Points.
{64526}{64646}I'm offering my boy, to form an|alliance with you...
{64586}{64716}...against Bill Cutting and his|slate of Native candidates.
{64676}{64812}I'll negotiate a handsome fee, for|every Irish vote...
{64744}{64867}...you send Tammany's way, in the|coming elections.
{64866}{64962}I need a new friend in the Five|Points, son.
{65017}{65084}I'd like that friend to| be you.
{65155}{65238}Now just a moment, Mr. Tweed.
{65222}{65314}Suppose we do get you those votes.
{65354}{65472}Would you back an Irish candidate|of my chosing..
{65412}{65446}I don't think so.
{65429}{65510}What if we get you all the|Irish votes?
{65470}{65644}Mr. Vallon, that will only happen|in the reign of Queen Dick!
{65628}{65668}Beg your pardon?
{65648}{65712}That means it will never happen.
{65680}{65810}Now I might be persuaded to back|an Irish candidate...
{65744}{65798}...for, let's say alderman.
{65772}{65790}Alderman?
{65792}{65888}We've already got an Irish|alderman.
{65840}{65884}So we have, that's why....
{65862}{65928}What's bigger than an alderman?
{65960}{65994}Sheriff!
{65998}{66034}Sheriff!
{66024}{66176}Alright, Mr Tweed, you back an|Irishman for sheriff...
{66100}{66186}...of the city and county of|New York...
{66144}{66240}...and we'll get him elected.
{66192}{66248}I love the Irish, son...
{66220}{66328}..but higher than alderman you|shall never climb.
{66274}{66312}Why not?
{66308}{66444}For one thing, no man living can|consolidate the Irish vote.
{66376}{66398}I can!
{66386}{66464}And for another, I mean no|offence...
{66442}{66514}...no one's yet found an Irish|candidate...
{66478}{66552}...for sheriff worth voting for.
{66602}{66626}Monk!
{66658}{66678}Here.
{66800}{66916}Got me looking as sober as me own|grandfather!
{66858}{66924}He was a great man, I'm sure.
{66902}{66984}He was a drunken bastard.
{67018}{67074}Can I say what I want?
{67088}{67150}That's why I wanted you.
{67148}{67288}Our elected representatives are a|gang of thieves!
{67218}{67298}Who swear to better our lot...
{67270}{67360}...while dipping their hands deep|into our pockets.
{67328}{67554}I stand shoulder to shoulder with|community leaders like Bill Cutting...
{67440}{67636}....against any, an all in roads in|our democracy.
{67538}{67622}I'll see to it, that no one|takes away...
{67590}{67694}... what you earned by pluck and application.
{67642}{67754}To invading hordes of Hibernians.
{67696}{67784}Go to the polls and put|your mark...
{67748}{67846}... next to the name Walter McGinn.
{67798}{67926}Against the potatoes weeders, like|them over there...
{67876}{67944}...thieving our jobs.
{67910}{68038}Why should so many Irish die down|south...
{67974}{68028}...when the first war to win...
{68000}{68102}...is not down in Dixie, but|right here...
{68052}{68102}...in these streets!
{68142}{68240} Who's the finest streetfighter in|the Five Points?
{68200}{68246}Monk!
{68232}{68372}That's right and let the whole|damn city hear it!
{68362}{68446}That man was right born for this.
{68404}{68552}He's killed 44 men and laid low a|couple of hundred more.
{68484}{68542}Is that right?
{68512}{68532}Right.
{68530}{68596}I should have run him for mayor!
{68628}{68678}Alright, line 'm up.
{68666}{68734}It's election day!
{68946}{69012}Come on, you bastard. We need|your vote.
{68988}{69080}Bastard? I fought for you|nigger...
{69042}{69098}...I lost an arm for you!
{69070}{69154}Well, that's a start. Come on.
{69112}{69202}Rise and shine, rise and shine.
{69170}{69322}This great country of ours, even|hop fiends get their vote.
{69276}{69368}Less heart and more haste,|darling.
{69322}{69370}Where are you going ?
{69346}{69414}I already voted today.
{69388}{69494}Cast for Monk and Tammany, by god!
{69448}{69478}Twice.
{69462}{69494}Twice?
{69486}{69580}Only twice? You call that doing|your civic duty?
{69538}{69574}Come with me.
{69564}{69672}Oh no, you don't. Get back and|sit down.
{69626}{69690}Here's another one!
{69662}{69696}Clean him up good.
{69678}{69818}Shave the beards off boys and send|them back to vote again.
{69748}{69836}Okay boys, vote Tammany.
{69798}{69854}Tammany!
{69826}{69976}What our great city needs is a new|court house.
{69900}{70036}Now I propose it should be a|modest, economical structure.
{69968}{70020}Excuse me one moment.
{69994}{70014}What is it?
{70018}{70202}Monk's already won by 3,000 more|votes, then there are voters.
{70110}{70186}Only 3? Make it 20, 30.
{70148}{70248}We don't need a victory, we need a|Roman triumph.
{70198}{70292}We don't have anymore ballots.
{70258}{70348}Remember the first rule of|politics...
{70302}{70374}...ballots don't make the results...
{70338}{70480}..the counters do. Keep counting.
{71182}{71230}It's from Bill.
{71310}{71334}Monk?
{71820}{71916}Citizens of the Five Points!
{71904}{72022}Mr. Cutting is attempting to|draw me...
{71964}{72018}...into an argument...
{72002}{72080}...that would no doubt end in|bloodshed...
{72042}{72140}...and the compromising of my|office.
{72128}{72180}What do you think?
{72196}{72358}Shall I engage in silence, this|relic of the ancient law...
{72288}{72438}...or, shall I be your chosen|voice...
{72364}{72512}...in a new testament, in a new|world?
{72586}{72632}There you are, Bill.
{72668}{72726}The people have spoken.
{72754}{72894}The very notion of violent|reprisal benumbs them.
{72904}{72930}Come on up.
{72958}{73002}Let's see if we can resolve our...
{72980}{73046}...grievances the democratic way.
{73598}{73776}That my friends, is the minority|vote.
{73736}{73866}Now you tasted my mutton, how do|you like it?
{73840}{73974}Look, I want you to see this.
{74004}{74090}This is you, right here!
{74058}{74230}Notch 45, you Irish bug bastard.
{74424}{74476}Why don't you burn him?
{74450}{74538}See if his ashes turn green.
{74638}{74732}Fortune favours them all!
{75002}{75076}You killed an elected official?
{75066}{75120}Who elected him?
{75094}{75174}You don't know what you've done|to yourself.
{75304}{75366}I know your works.
{75378}{75462}You're neither cold nor hot.
{75434}{75530}So because you are luke warm...
{75482}{75582}...I will spew you out of my|mouth.
{75578}{75702}You can build your filthy world|without me.
{75640}{75768}I took the father, now I'll take|the son.
{75704}{75828}You tell young Vallon, I'm going|to paint...
{75766}{75854}...Paradise square with his blood.
{75822}{75886}Two coats!
{75882}{75998}I'll festoon my sleeping|chamber with his guts.
{75940}{76056}As for you Mr. Tammany|fucking hall...
{75998}{76116}...you come down to the Points|once more...
{76056}{76196}...and you'll be dispatched by my|own hand!
{76190}{76248}Now get back to your|celebration...
{76218}{76296}...and let me eat in peace.
{76258}{76312}I paid you fair.
{76892}{76916}Down!
{76952}{76972}Raise!
{78022}{78070}You son of a bitch!
{78168}{78196}Challenge.
{78248}{78298}Challenge accepted.
{79544}{79600}And then it came...
{79596}{79674}...the first day of the draft.
{79634}{79670}Thomas O'neill.
{79682}{79722}Andrew Lewis.
{79738}{79788}Joseph Flynn.
{79762}{79924}They read out the draftees names|as if they were dead already.
{79892}{79956}J.B. Gleeson.
{79958}{79994}The O'Conell Guard.
{80000}{80034}The Plug Uglies.
{80026}{80042}As for us.
{80034}{80074}The Forty Thieves.
{80058}{80106}The tribes were gathered.
{80108}{80148}The Chichesters.
{80128}{80192}The drums were beating.
{80174}{80210}The Dead Rabbits.
{80210}{80256}The American guard.
{80252}{80300}The Atlantic Guard.
{80284}{80336}The Slaughterhouses.
{80310}{80372}The Bowery Boys.
{80352}{80438}Confederation of American Natives.
{80444}{80488}James Mooney.
{80476}{80536}But all we could see...
{80526}{80600}...was the hand in front of us.
{80562}{80604}Shaun O'Connell.
{80626}{80702}C.W. Morris.
{80722}{80748}When?
{80746}{80802}Whenever you like.
{80784}{80832}Daybreak tomorrow.
{80820}{80842}Ground?
{80854}{80884}Paradise square.
{80902}{80928}Weapons?
{80944}{81006}That I leave up to you.
{80992}{81082}Bricks, bats, axes, knives.
{81078}{81116}Pistols?
{81154}{81202}No pistols.
{81208}{81258}Good boy.
{81322}{81374}Terms are resolved.
{81348}{81400}Counsel is concluded.
{81546}{81614}To hell with your damned draft.
{81588}{81644}Get 'm boys.
{81616}{81668}Rip 'm apart.
{81830}{81900}Kill the rich bastards.
{82040}{82084}Hotel!
{82116}{82202}They're not getting my son!
{82294}{82386}Uptown town at the draft office...
{82356}{82454}...the cops broke a few skulls.
{82420}{82494}And everybody ran away.
{82502}{82580}But the word was spreading...
{82566}{82630}...in the dark.
{82638}{82800}Up on fifth avenue, the Schermerhorns|and their mob...
{82720}{82806}...breathed a little easy.
{82762}{82912}Just a brief blist of anger, over|Mr. Lincoln's draft.
{82838}{82926}Entirely justifiable in my view.
{82894}{82964}There are two sides to that|question.
{82928}{83052}Ther are several sides to that|question, Mr. Schermerhorn.
{82990}{83068}But only one right side.
{83030}{83136}As with any question, it|holds the abuse...
{83082}{83132}...of any executive power.
{83108}{83200}In any case, Mr. Greely...
{83154}{83296}...we can all be thankful, it|wasn't any worse.
{83238}{83318}It may be worse yet, sir.
{83278}{83360}I saw them. I don't know|what to think...
{83318}{83454}What is it you are so fond of|saying, Mr. Tweed?
{83386}{83472}Mr. Greely, you won't like this...
{83430}{83482}...but what is it?
{83456}{83508}I don't remember.
{83482}{83608}You can always hire one half| of the poor...
{83544}{83618}...to kill the other half.
{83848}{83912}I've come to say goodbye.
{83912}{84002}I've booked passage for|California.
{84042}{84144}Jenny, give me one more day and|I'll go with you.
{84112}{84174}You'll be dead by then.
{84182}{84242}What would you have me do?
{84212}{84252}I don't know.
{84328}{84400}This will all be finished|tomorrow.
{84376}{84426}No it won't.
{84508}{84608}This whole place is going to|burn anyway.
{84776}{84938}I've heard of the poor are going|from door to door...
{84858}{85072}...in the Five Points, asking those|supporters for further riots...
{84978}{85082}...to place a candle in the|window.
{85064}{85150}Irish, Poles, Germans.
{85134}{85274}Ah, Mr. Greely, the city is not mad...
{85218}{85332}...I prophesise a dark night.
{85820}{85886}Nobody goes to work today.
{85862}{85952}We're shutting the factories down!
{85906}{85996}When the sun rose next...
{85962}{86052}...the city had split in half.
{86022}{86116}From all over New York|they came...
{86068}{86198}...ironworkers, factory boys,|street cleaners!
{86134}{86224}Irish, Polish, German...
{86178}{86312}...anyone who never cared about|slavery in the Union.
{86258}{86334}Anyone who couldn't buy his way out.
{86322}{86376}Let the sons of the rich...
{86348}{86420}....go and die they cried.
{86396}{86460}Let the sons of the poor...
{86428}{86486}...stay home.
{86496}{86578}The earth was shaking now.
{86562}{86668}But I was about my father's business.
{86976}{87046}Oh, mighty Lord...
{87032}{87136}...you are the dagger in|my hand.
{87110}{87224}Guide my hand on this day of|vengeance.
{87168}{87268}We give thanks to the Lord....
{87228}{87302}...for He is good.
{87278}{87388}With you, the swift cannot flee.
{87334}{87426}Nor the strong escape.
{87380}{87582}Let my sword devour, till its thirst|is quenched with blood....
{87480}{87570}...and my enemy sleeps forever.
{87538}{87648}For you and the God of|retribution.
{87592}{87712}For the Lord crushes the wicked.
{87652}{87740}The Lord is merciful.
{87738}{87888}And his love endures forever.
{87838}{87872}Amen.
{87856}{87890}Amen.
{87872}{87910}Amen.
{88212}{88260}Get the women upstairs!
{88462}{88564}From 18th precinct. The mob is|ransacking houses...
{88514}{88596}....in 27th street and 7th|avenue.
{88554}{88636}We have no force to send.
{88596}{88648}From 15th precinct.
{88622}{88726}All the stores are closing on|8th avenue.
{88674}{88770}From fear of the mob in 17th|street.
{88838}{88862}From 4th.
{88850}{88962}The rioters are attacking|coloured boarding houses...
{88906}{88990}...robbing them and setting them|on fire.
{88948}{88988}From 21st.
{88968}{89062}The mob have just broken open|a gun store...
{89014}{89110}...on 3rd avenue and are arming.
{89254}{89348}Marshall's office on 3rd avenue|is burning down.
{89300}{89366}The police is of no avail.
{89334}{89396}Show yourself, please!
{89364}{89456}Two coloured men brought in|almost dead.
{89410}{89486}There are 50 more outside.
{89448}{89490}They need help.
{89470}{89554}The blacks are being attacked|all over the city.
{89512}{89606}There's the 300 dollar man!
{89564}{89586}Get him!
{89596}{89668}Did your daddy buy you out of|the army!
{89638}{89706}Can he buy me out of the|army too?
{89690}{89784}There is danger of mob|attacking armoury...
{89736}{89836}...corner 21st street, 2nd|avenue.
{89798}{89888}There's about 500 stand of arms|in it.
{90004}{90076}The line is dead. They're trying|to cut all the wires!
{90142}{90166}From 1st.
{90160}{90234}Riot at Pier 4, North River.
{90198}{90264}They have killed negros there.
{90230}{90338}A crowd is here and are going to|destroy the station.
{90378}{90418}Get her bag!
{90408}{90434}Get her bag!
{90476}{90516}From 18th precinct.
{90508}{90566}The mob have attacked the|armoury.
{90536}{90602}...on 2nd avenue an 21st street.
{90570}{90668}There is danger of fire in the|building.
{90626}{90744}All 300 police wounded or|unaccounted for.
{90732}{90752}From 20th.
{90748}{90832}Send 100 men to disperse mob....
{90838}{90920}Building corner 33rd street, 2nd|avenue...
{90888}{90948}...set on fire by the mob.
{90952}{91036}Barnum's American museum on|fire!
{91002}{91048}Animals are escaping.
{91050}{91106}Let go!
{91456}{91640}Gunboat Liberty! An ironclad berth now|lying on the foot of Wall street.
{91548}{91636}They're ready to open fire on|the mob!
{91592}{91672}The mob are now going to 5th|avenue...
{91632}{91704}....to attack the Tribune office.
{91686}{91718}From 16th.
{91702}{91782}The mob is coming down to|station house.
{91742}{91784}We have no men!
{91798}{91882}From 16th. The seventh regiment|has arrived....
{91840}{91900}...on the foot of Canal street.
{91870}{91926}They're on their way to|Bog Wade.
{91936}{92014}The mob is about 4500 strong.
{91986}{92048}They are going to burn down|Harlem Bridge.
{92030}{92094}Harlem Bridge is to be torched!
{92080}{92152}The rats have taken over|the city!
{92230}{92374}From 21st. There's an attack on|the coloured people in 2nd avenue.
{92302}{92402}There's a mob headed for the|coloured orphan's asylum.
{92352}{92424}Send troops to protect the|children.
{92408}{92546}7th Avenue, 28th street. They|have just killed a negro.
{92478}{92510}There's a negro!
{92494}{92534}Get him!
{92514}{92600}Sir, the major general wants to|know what to do....
{92556}{92582}...with the prisoners captured.
{92570}{92614}Prisoners? Don't take any.
{92592}{92664}The mob isn't taking any|prisoners!
{92638}{92684}Put the mob down!
{92662}{92800}Don't take a prisoner till|you've put the mob down!
{92910}{92976}Soldiers now on 38th street.
{92954}{93022}The mob will not disperse!
{93004}{93050}What are your orders?
{93036}{93094}What are your orders?
{93632}{93648}Here the come!
{93710}{93752}Let's stick together!
{93838}{93912}Troop. Halt!
{93902}{93994}Present arms!
{94100}{94168}On your order, Vallon!
{94238}{94356}I order you to disperse.
{94386}{94446}Fire!
{95280}{95350}Fire!
{95694}{95736}Fire!
{96218}{96282}Drive them into the square.
{96326}{96374}Bill!
{96660}{96708}Bill!
{99130}{99172}Bastards!
{99150}{99204}Shang!Hold on!
{99992}{100080}Thank God.
{100064}{100130}I die a true American.
{103064}{103102}Tomorrow morning...
{103081}{103159}...get our people down to|the docks.
{103138}{103244}I want every man and woman|coming off the boats...
{103198}{103274}...given hot soup and bread.
{103359}{103481}We're burying a lot of votes|here tonight.
{103868}{103920}In the end....
{103894}{103983}...they put candles on the|bodies...
{103938}{104074}...so their friends, if they|had any...
{104031}{104107}...could know them in the dark.
{104111}{104230}The city did this free|of charge.
{104222}{104478}Shang, Jimmy Spoils, Hellcat.|McGloin and more.
{104406}{104480}Friend or foe...
{104457}{104544}...it didn't make no difference|now.
{104983}{105061}It was four days and nights...
{105022}{105172}..before the worst of the mob|was finally put down.
{105148}{105266}We never knew how many New|Yorkers died...
{105206}{105340}...that week, before the city|was finally delivered.
{105320}{105508}My father told me we was all|born of blood and tribulation.
{105464}{105635}And so then too, was our|great city.
{105638}{105702}But for those of us who...
{105670}{105792}...lived and died in them|furious days...
{105756}{105844}...it was like everything we|knew...
{105811}{105908}...was mildly swept away.
{105904}{106068}And no matter what they did to|build this city up again...
{106032}{106108}...for the rest of time...
{106124}{106264}...would be like no one ever|knew we were here.